### ISSUE TITLE
入门 - 第六章 - 粒子喷雾  缺少贴图的代码

### ISSUE THREAD

**Issue by ggggxiaolong** [shawn0326/babylon-doc-cn#2]
1. `它们还被指定了贴图，来赋予它们的外观。`
这句之后缺少了跟着的代码块
`particleSystem.particleTexture = new BABYLON.Texture("url to image", scene);`

2. `粒子都是从一个特定的立方体区域发射的。每个粒子拥有一个生命周期，每次粒子生命结束后会重新发射。`
这句应该在 `它们还被指定了贴图，来赋予它们的外观。`之后

**Comment by shawn0326** [comment]
感谢反馈，已对照英文原文做了修改。
